services:
  api:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: yomitoku-fastapi-server:latest
    stop_grace_period: 0s
    ipc: host
    ports:
      - "3200:3000"
    volumes:
      # - .:/workspace
      - ~/.cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [gpu]
